---
# These tasks start the grumble docker container

- name: Ensure container is started
  community.docker.docker_container:
    container_default_behavior: compatibility
    name: grumble
    image: grumble
    volumes:
      - "{{ grumble_dir }}:/data"
    ports:
      - "64738:64738/tcp"
      - "64738:64738/udp"
