---
# these tasks install and configure chrony ntp servers

- name: Update apt cache if older than 3600 seconds
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
- name: Ensure chrony is installed
  become: true
  ansible.builtin.apt:
    name: chrony
    state: present
- name: Create chrony configuration from template
  become: true
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: "/etc/chrony/chrony.conf"
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart chrony
