---
# These tasks start the grumble docker container

- name: run grumble container
  hosts: localhost

  tasks:
  - name: ensure docker service is started
    become: true
    service:
      name: docker
      state: started
  - name: ensure container is started
    community.docker.docker_container:
      container_default_behavior: compatibility
      name: grumble
      image: grumble
      volumes:
        - "{{ ansible_env.HOME }}/.grumble:/data"
      ports:
        - "64738:64738/tcp"
        - "64738:64738/udp"
