---
# these tasks configure the openvpn client

- name: Create openvpn client config file
  ansible.builtin.template:
    src: client.conf.j2
    dest: "/etc/openvpn/client/{{ client }}.conf"
    owner: openvpn
    group: network
    mode: '0600'
- name: Copy certificates and keys
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "/etc/openvpn/client/{{ item.dest }}"
    owner: openvpn
    group: network
    mode: '0600'
  loop:
    - {src: "{{ ca_cert }}", dest: "ca.crt"}
    - {src: "{{ client_cert }}", dest: "{{ client }}.crt"}
    - {src: "{{ client_key }}", dest: "{{ client }}.key"}
