---
# these tasks configure the openvpn client

- name: create openvpn client config file
  template:
    src: client.conf.j2
    dest: "/etc/openvpn/client/{{ client }}.conf"
    owner: openvpn
    group: network
    mode: '0600'
