---
# these tasks add an ansible user with an authorized ssh key and add it to
# sudoers without password

- name: Add user with username and authorized ssh key and sudo
  hosts: ansible_hosts
  become: true
  vars:
    username: "ansible"
    key_file: "id_rsa.pub"

  tasks:
    - name: Add the user
      ansible.builtin.user:
        name: "{{ username }}"
        comment: Ansible User
        password: '!'
    - name: Add user to the sudoers
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ username }}"
        content: "{{ username }}  ALL=(ALL)  NOPASSWD: ALL"
        owner: root
        group: root
        mode: '0440'
    - name: Set authorized key for user from file
      ansible.posix.authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', '{{ key_file }}') }}"
