---
# these tasks install and configure chrony ntp servers

- name: Install and configure chrony ntp servers
  hosts: ntp_servers
  become: true
  vars:
    allows:
      - 192.168.1.0/24
      - 192.168.2.0/24
      - 192.168.3.0/24

  tasks:
    - name: Ensure chrony is installed
      ansible.builtin.apt:
        name: chrony
        state: present
    - name: Create chrony configuration from template
      ansible.builtin.template:
        src: chrony.conf.j2
        dest: "/etc/chrony/chrony.conf"
        owner: root
        group: root
        mode: '0644'
      notify:
        - Restart chrony

  handlers:
    - name: Restart chrony
      ansible.builtin.service:
        name: chrony
        state: restarted
