---
# these tasks setup dhcpd with static host configuration

- name: Setup dhcpd
  hosts: dhcp_servers
  become: true
  vars:
    subnets:
      - ip: 192.168.1.0
        netmask: 255.255.255.0
        routers: 192.168.1.1
        dns_servers: 192.168.1.1
        ntp_servers: 192.168.1.1
        domain_name: company.lan
        hosts:
          - name: host1
            mac: DD:DD:DF:E5:F7:D7
            ip: 192.168.1.2
          - name: host2
            mac: 00:01:02:38:AC:45
            ip: 192.168.1.3

  tasks:
    - name: Update apt cache if older than 3600 seconds
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Ensure dhcpd is installed
      ansible.builtin.apt:
        name: isc-dhcp-server
        state: present
    - name: Create dhcpd configuration from template
      ansible.builtin.template:
        src: dhcp.conf.j2
        dest: "/etc/dhcp/dhcpd.conf"
        owner: root
        group: root
        mode: '0644'
      notify:
        - Restart dhcpd

  handlers:
    - name: Restart dhcpd
      ansible.builtin.service:
        name: isc-dhcp-server
        state: restarted
