---
# these tasks configure the wireguard client

- name: Create wireguard client config file
  ansible.builtin.template:
    src: wg.conf.j2
    dest: "/etc/wireguard/{{ interface }}.conf"
    owner: root
    group: root
    mode: '0600'
