---
# these tasks set ssh keys for users

- name: Set ssh keys
  become: true
  ansible.posix.authorized_key:
    user: '{{ item }}'
    state: present
    key: "{{ lookup('file', inventory_dir + '/ssh-keys/' + item, split_lines=false) }}"
    exclusive: true
  loop: "{{ ssh_users }}"
