---
# these tasks connect to a wireguard server

- name: start wireguard vpn connection
  hosts: localhost
  vars:
    - wg_conf: "{{ ansible_env.HOME }}/wireguard/wg0.conf"

  tasks:
    - name: install wireguard tools
      community.general.pacman:
        name:
          - wireguard-tools
        state: present
    - name: connect wireguard
      ansible.builtin.command:
        cmd: /usr/bin/wg-quick up "{{ wg_conf }}"
